services:
  api:
    build: .
    container_name: transporte_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=transportedb
      - POSTGRES_USER=transporteuser
      - POSTGRES_PASSWORD=supersecretpass
      - Jwt__Key=esta_es_una_clave_super_secreta_y_larga_para_seguridad_12345
      - Jwt__Issuer=TransportApi
      - Jwt__Audience=TransportClient
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: transporte_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: transportedb
      POSTGRES_USER: transporteuser
      POSTGRES_PASSWORD: supersecretpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transporteuser -d transportedb"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data: